name: Test Python App
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi pytest httpx sqlalchemy uvicorn
      
      - name: Run tests
        run: |
          python -m pytest tests/ -v